Fixes #1620: reference patched FSAC attempting to fix stuck code lenses
ionide/ionide-vscode-fsharp pull request #1626
Opened 2021-11-11 07:05 UTC by beauvankirk

This change attempts to address the broken code lenses with the recent 5.9.0 release as raised in [1620](https://github.com/ionide/ionide-vscode-fsharp/issues/1620). 

The issue appears to be rooted in a change in the FSAutoComplete update, wherein the LspServer.CodeLensResolve method was altered to call an Option<_>-returning function (TryGetRecentTypeCheckResultsForFile in 0.49.0)  rather than an Async<Option<_>>-returning function (TryGetLatestTypeCheckResultsForFile in 0.48.1) to check for FCS Checker results. The line with the new call is [here](https://github.com/fsharp/FsAutoComplete/blob/7fdc3fe88ffc551bd9a68349bd90dc118b64c4ab/src/FsAutoComplete/FsAutoComplete.Lsp.fs#L1895)

I'm not sure this is the best fix, but I revised the CodeLensResolve to instead call GetLatestTypeCheckResultsForFile, which returns an Async<_>. This seems to (correctly in my opinion) wait for FCS check results before resolving the code lens. The method I opted for is also the one that retained the same comment as the previous version's variant, so it seems perhaps that was the intended more-direct replacement?

If this seems reasonable I can open a PR on FSAC as well/instead. I wanted to start here since this is the only place the issue was raised.

Naturally a merged PR on FSAC would eliminate the need for any code change here. For now I was including these changes (which merely reference my FSAC branch) for initial feedback and to make sure CI/tests weren't any worse off.

For reference, this was a helpful diff view relating the relevant FSAC change:

![image](https://user-images.githubusercontent.com/20178486/141252961-c8059d3c-294c-44c4-8f55-71c139f193f8.png)

2021-11-11 09:42 UTC, forki requested changes

2021-11-11 09:42 UTC, forki commented on paket.dependencies
> +git https://github.com/beauvankirk/FsAutoComplete.git bugfix/stuck-code-lenses build:"build.cmd", OS: win
@Krzysztof-Cieslak please merge this to your own FSAC fork and reference that one :P

2021-11-11 11:47 UTC, Krzysztof-Cieslak commented
Hey, can you please open PR against FSAC repo? Thanks.

2021-11-11 13:37 UTC, beauvankirk commented
> Hey, can you please open PR against FSAC repo? Thanks.

@Krzysztof-Cieslak [PR opened](https://github.com/fsharp/FsAutoComplete/pull/852) per your request.

Thanks! Let me know if it can be revised/improved in any way.

2021-11-15 14:07 UTC, closed without merging

2021-11-15 14:11 UTC, beauvankirk commented
Closing as issue was resolved with merge of FSAC PR and release (0.49.1) and updated reference to that in new release here (5.9.1). Thanks again @Krzysztof-Cieslak